# Generated by Django 4.2.28 on 2026-02-28 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='booking',
            name='bookings_trip_id_2e5547_idx',
        ),
        migrations.RemoveIndex(
            model_name='booking',
            name='bookings_travele_94b049_idx',
        ),
    ]
