# Generated by Django 4.2.28 on 2026-02-28 19:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vendors', '0001_initial'),
        ('reviews', '0001_initial'),
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='vendors.agency'),
        ),
        migrations.AddField(
            model_name='review',
            name='traveler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='trips.trip'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['trip'], name='reviews_trip_id_a9e51b_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['agency'], name='reviews_agency__47c49b_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['traveler'], name='reviews_travele_0b565d_idx'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.CheckConstraint(check=models.Q(('trip_id__isnull', False), ('agency_id__isnull', False), _connector='OR'), name='review_target_trip_or_agency'),
        ),
    ]
