# Generated by Django 4.2.28 on 2026-02-28 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='review',
            name='reviews_trip_id_a9e51b_idx',
        ),
        migrations.RemoveIndex(
            model_name='review',
            name='reviews_agency__47c49b_idx',
        ),
        migrations.RemoveIndex(
            model_name='review',
            name='reviews_travele_0b565d_idx',
        ),
    ]
