# Generated by Django 4.2.28 on 2026-02-28 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendors', '0001_initial'),
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='vendors.agency'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['destination'], name='trips_destina_6a1240_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['agency'], name='trips_agency__d8cc05_idx'),
        ),
    ]
