# Generated by Django 4.2.28 on 2026-02-28 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='trip',
            name='trips_agency__d8cc05_idx',
        ),
    ]
