# Generated by Django 4.2.28 on 2026-02-28 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='passwordresettoken',
            name='password_re_user_id_af59e2_idx',
        ),
        migrations.RemoveIndex(
            model_name='refreshtoken',
            name='refresh_tok_user_id_46676d_idx',
        ),
    ]
